name: cuisine

services:
  web:
    build: ./dockerfile
    container_name: cuisine-php-web
    ports:
      - "8080:80"
    volumes:
      - ./../:/var/www/html:Z
    depends_on:
      - db
    networks:
      - cuisine-network

  db:
    image: mysql:8.0
    container_name: cuisine-php-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpdb
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: phppass
    volumes:
      - db-data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    networks:
      - cuisine-network

  adminer:
    image: adminer:latest
    container_name: cuisine-php-adminer
    ports:
      - "8081:8080"
    networks:
      - cuisine-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  cuisine-network:
    driver: bridge